package dev.dshtabs

import android.content.Context
import android.util.Base64
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import com.jcraft.jsch.JSch
import com.jcraft.jsch.KeyPair
import java.io.ByteArrayOutputStream
import java.io.File

/**
 * The app's own SSH key, and the reason it exists.
 *
 * A phone is the worst place to type a password: the operator is on a train, the
 * password manager is on another device, and the on-screen keyboard is a shoulder
 * to look over. The alternative is a key, which means this app has to generate
 * one, keep it, and show the half that gets pasted into `authorized_keys`.
 *
 * **Ed25519, generated by JSch.** That works only because BouncyCastle is a
 * dependency — the same finding that made the handshake work at all. JSch's
 * `genKeyPair(jsch, ED25519)` goes through exactly the class Android's runtime
 * cannot load on its own, so this file and that dependency are one decision, not
 * two.
 *
 * **How the private half is protected.** It is written with a passphrase, and the
 * passphrase is a random 32-byte value kept in `EncryptedSharedPreferences`, whose
 * master key lives in the Android Keystore. So the key on disk is ciphertext, and
 * the thing that decrypts it is hardware-backed where the device supports it. The
 * alternative — an unencrypted key in app storage — is what OpenSSH does on a
 * desktop with `0600`, and it is defensible on a phone too; this is the stricter
 * version and costs one generated value.
 *
 * This is not a defence against someone holding an unlocked, rooted device. It is
 * a defence against a key that outlives the app: a backup, a file manager, or a
 * copy made while debugging.
 */
object Keys {

	private const val DIRECTORY = "keys"
	private const val PRIVATE = "id_ed25519"
	private const val PREFERENCES = "dsh-tabs-keys"

	/** The comment written next to the public key, so a human can tell them apart. */
	private const val COMMENT = "dsh-tabs-android"

	@Volatile
	private var appContext: Context? = null

	fun init(context: Context) {
		appContext = context.applicationContext
	}

	private fun requireContext(): Context = appContext ?: error("Keys.init() has not been called")

	private fun privateKeyFile(): File = File(File(requireContext().filesDir, DIRECTORY), PRIVATE)

	/** True when this app has a key of its own to offer. */
	fun exists(): Boolean = privateKeyFile().exists()

	/** For diagnostics: where the key lives, and how big it is. */
	fun describe(): String {
		val file = privateKeyFile()
		return "path=${file.absolutePath} exists=${file.exists()} bytes=${if (file.exists()) file.length() else 0} hasPassphrase=${passphrase() != null}"
	}

	/**
	 * The public half, as one line ready for `authorized_keys`.
	 *
	 * @return the key, or null when none has been made yet — or when one exists and
	 *   cannot be read, which [publicKeyOrError] exists to tell apart.
	 */
	fun publicKey(): String? = publicKeyOrError().first

	/**
	 * The public key, or the reason there is not one.
	 *
	 * `publicKey()` returning null for two very different situations — "no key yet"
	 * and "there is a key and this app cannot read it" — is the kind of silence that
	 * turns a one-line fix into an afternoon. Measured: generation reported success,
	 * the file was on disk, and the very next read came back null.
	 *
	 * @return the key or null, and the failure when there was one.
	 */
	fun publicKeyOrError(): Pair<String?, String?> {
		if (!exists()) return null to null
		val secret = passphrase() ?: return null to "no passphrase is stored"
		val file = privateKeyFile()
		if (!file.exists()) return null to "the key file is missing: ${file.absolutePath}"
		return try {
			// **Not** `KeyPair.load(jsch, path, passphrase)`. That signature is
			// `(prvfile, pubfile)` — the second argument is the path of a `.pub` file —
			// so passing a passphrase there makes JSch try to open a file named after
			// the passphrase and fail with `FileNotFoundException` naming it, which is
			// exactly what happened. Reading a file needs no `KeyPair` at all: the bytes
			// go in, the key comes out, and the passphrase is used for what it is.
			val pair = KeyPair.load(JSch(), file.readBytes(), null)
			if (pair.isEncrypted) pair.decrypt(secret)
			val public = ByteArrayOutputStream().use { out ->
				pair.writePublicKey(out, COMMENT)
				out.toString("UTF-8").trim()
			}
			pair.dispose()
			public to null
		} catch (error: Throwable) {
			null to "${error.javaClass.name}: ${error.message}"
		}
	}

	/**
	 * Generate a key, or return the one that already exists.
	 *
	 * Regenerating silently would lock the operator out of every machine that has
	 * the old public key, so this refuses rather than replaces — rotating a key is a
	 * deliberate act, and it belongs to a button that says so.
	 *
	 * @return the public key in `authorized_keys` form.
	 */
	fun generate(): String {
		if (exists()) return publicKey() ?: error("a key exists but could not be read")

		val value = newPassphrase()
		val pair = KeyPair.genKeyPair(JSch(), KeyPair.ED25519)
		val public: String
		try {
			// Read the public half *before* disposing the pair. `dispose()` clears the
			// key material, so asking afterwards fails with "key is not available" — and
			// the write below has already happened, which would leave the app holding a
			// key it cannot show.
			public = ByteArrayOutputStream().use { out ->
				pair.writePublicKey(out, COMMENT)
				out.toString("UTF-8").trim()
			}

			val target = privateKeyFile()
			target.parentFile?.mkdirs()
			// OpenSSH's own private key format, which is what `ssh-keygen -p` and
			// everything else expect to find.
			pair.writeOpenSSHv1PrivateKey(target.absolutePath, value.toByteArray(Charsets.UTF_8))
			// Owner-only, beside the encryption rather than instead of it.
			target.setReadable(false, false)
			target.setWritable(false, false)
			target.setReadable(true, true)
			target.setWritable(true, true)
		} finally {
			pair.dispose()
		}

		storePassphrase(value)
		return public
	}

	/**
	 * Forget the key, and the passphrase with it.
	 *
	 * Called by the rotation button. It does not touch any machine: the old public
	 * key stays in every `authorized_keys` until somebody removes it, which is the
	 * honest behaviour — an app cannot reach into those files, and pretending
	 * otherwise would be worse than saying so.
	 */
	fun forget() {
		privateKeyFile().delete()
		preferences()?.edit()?.remove(PASSPHRASE)?.apply()
	}

	/**
	 * The credential to authenticate with, preferring the key.
	 *
	 * The key is chosen when it exists and a password is used only when it does not,
	 * because a machine that has been set up with the public key should never ask for
	 * anything — and one that has not will fail the key attempt and say so in the
	 * transcript, which is more useful than silently falling back to a prompt.
	 *
	 * @param typedPassword what the operator entered, used only when there is no key.
	 */
	fun credentialFor(typedPassword: String?): Credential {
		val secret = passphrase()
		if (exists() && secret != null) return Credential.PrivateKey(privateKeyFile().readBytes(), secret)
		return Credential.Password(typedPassword.orEmpty())
	}

	// ------------------------------------------------------------- passphrase

	private const val PASSPHRASE = "passphrase"

	private fun preferences(): android.content.SharedPreferences? = try {
		val context = requireContext()
		val master = MasterKey.Builder(context)
			.setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
			.build()
		EncryptedSharedPreferences.create(
			context,
			PREFERENCES,
			master,
			EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
			EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
		)
	} catch (error: Exception) {
		// A device whose keystore refuses to cooperate still has a usable app, minus
		// the remembered key. Failing here would take the whole client down for a
		// feature the operator can live without.
		null
	}

	private fun newPassphrase(): String {
		val bytes = ByteArray(32)
		java.security.SecureRandom().nextBytes(bytes)
		return Base64.encodeToString(bytes, Base64.NO_WRAP)
	}

	private fun storePassphrase(value: String) {
		preferences()?.edit()?.putString(PASSPHRASE, value)?.apply()
	}

	private fun passphrase(): String? = preferences()?.getString(PASSPHRASE, null)
}
